### ISSUE TITLE
Error message "Anti-hacking system detected"

### ISSUE THREAD

**Issue by yossi1114net** [develsoftware/GMinerRelease#10]
After I updated NVIDIA drivers to the latest version, I get the following message when I run the miner.

> 10:39:24 Anti-hacking system detected modification of the miner memory. If you using an antivirus, add miner to antivirus exceptions
10:39:24 Miner terminated, watchdog will restart process after 10 seconds

Tried disabling firewalls in Windows Defender but no success. Also tried Gminer v1.37 and v1.38. Any ideas?

NVIDIA Driver version: 430.39
OS: Microsoft Windows [Version 10.0.17763.437]
CPU: Intel Core i7-7700K
GPU cards: GTX 1080 Ti x1 and GTX 1060 x1

<img width="1232" alt="Screen Shot 2019-04-25 at 21 37 53" src="https://user-images.githubusercontent.com/14039768/56778431-3a2f8100-67a4-11e9-981d-044a67f92b54.png">

**Comment by ntminer** [comment]
i got the same error when i modified windows's path environment variable append my custom dir

**Comment by yossi1114net** [comment]
Newer version fixed this issue. Thank you.
