### ISSUE TITLE
Fee

### ISSUE THREAD

**Issue by frode88** [develsoftware/GMinerRelease#104]
Hi. What is the fee for Ethash? And the miner use more power then all other competitors for AMD out there.
Btw last update doing super duper good job on hashrate.

**Comment by develsoftware** [comment]
Hi, DevFee on Ethash is 0.65%

**Comment by frode88** [comment]
@develsoftware Thank you:) been wating to long to get Gminer working with good hashrate/shares. Please take a look at power usage.. :)  thank you.

**Comment by frode88** [comment]
@develsoftware Just info. Tested the miner on hiveos. the miner keep restart every 10-15 for no reason. just info for you:)

**Comment by frode88** [comment]
@develsoftware here is log. keep doing this every 10-15min, i cant see any gpu that crash or something,


<img width="624" alt="rig4" src="https://user-images.githubusercontent.com/22121200/100382182-08833980-301b-11eb-8cf8-00a3e0400635.PNG">

**Comment by develsoftware** [comment]
can you please ping me in telegram @evgeniy_pochitaev
