### ISSUE TITLE
Failed to initialize NVML (Nvidia driver 460.79 and above)

### ISSUE THREAD

**Issue by kydex** [develsoftware/GMinerRelease#106]
I get "Failed to initialize NVML" error using Nvidia Driver 460.79 and 460.89 (gminer 2.33)
457.51 and below works good.

**Comment by JRedOW** [comment]
I'm getting the same error.

**Comment by develsoftware** [comment]
we have fixed this bug in https://github.com/develsoftware/GMinerRelease/releases/tag/2.35
thank you for report

**Comment by kydex** [comment]
Thx!
