### ISSUE TITLE
Separate bad shares: incorrect, stale and rejected

### ISSUE THREAD

**Issue by megalolka** [develsoftware/GMinerRelease#109]
Hello!
Is it possible to make GMiner show incorrect shares, stale shares and rejected by the pool shares **separately**?
Like the PhoenixMiner does this.
Because incorrect shares are mostly caused by overclocking and miners should see that the overclocking should be adjusted.
And the other types of bad shared (stale or rejected by pool) doesn't require to make overlocking changes.

**Comment by develsoftware** [comment]
Hello,
Thank you for your suggestion, we will count it.
Best Regards.
