### ISSUE TITLE
GMiner sets my memory clock speed to 3004MHz and I can't change it (2.41v)

### ISSUE THREAD

**Issue by Volkann1234** [develsoftware/GMinerRelease#117]
When I start GMiner, my memory clock speed for gpu is not going higher than 3004MHz

GMiner: 2.41v
GPU: Geforce GTX 960
Driver Version: 457.30

When using GMiner:
![afterburner](https://user-images.githubusercontent.com/54782754/104106511-92374f80-52c7-11eb-93c4-8a8b4def1396.PNG)

When NOT using GMiner:
![before](https://user-images.githubusercontent.com/54782754/104106522-9a8f8a80-52c7-11eb-902f-e79d273cd317.PNG)

**Comment by DeeDeeRanged** [comment]
Is this still the case, if not pls. close the issue.
