### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by PiotrKFtw** [develsoftware/GMinerRelease#133]
It's solved i guess

**Comment by Freekers** [comment]
I have it running in a VM just fine. No special parameters needed.
Which error are you getting?

**Comment by PiotrKFtw** [comment]
Connection Error: end of file

**Comment by Freekers** [comment]
Without any more information about your setup, it's impossible to help you.

**Comment by PiotrKFtw** [comment]
Using nicehash, latest version of gminer, gpu rtx titan

**Comment by Freekers** [comment]
And which virtualization are you using? Anyway, a lot of information is missing from your issue. Contact nicehash support for help, for me this is too vague.

**Comment by PiotrKFtw** [comment]
Vmware also alright, thanks for trying to help anyway..
