### ISSUE TITLE
Miner stops reporting but continues working

### ISSUE THREAD

**Issue by BigGayLucy** [develsoftware/GMinerRelease#164]
Running 2x 3060 cards in my computer. Tried mining specific coins recently rather then using Nicehash. Went well. But with Gminer I've noticed an awful bug while mining CTXC on with Cortex. Thru the public 2Miners pool

On the screenshot it shows the last updated time, 15:28, at the time of writing it is 17:13. It's gone 2 hours with nothing new showing. This happened before but I thought it was simply me not receiving any new mining jobs. I checked my wallet on 2Miners, it updates regularly and it says my last share was 20 seconds ago. My unpaid mining balance also keeps going up, so I am still in fact mining effectively. I still see the same hashrate on the website too.
So its just something wrong with the client. It happens abruptly. My cards are OC'd and stable, they've been going for weeks with no faults on nicehash.

![Screenshot_20](https://user-images.githubusercontent.com/67293857/111184890-b65a2a00-85b1-11eb-9d2f-813dad5be415.png)

**Comment by thaneb** [comment]
I encountered same issue with binance pool and now with ethermine, gtx1660ti on laptop, rtx3060ti and 2070, press ctrl-c one time and all the missing console messages will appear...

**Comment by BigGayLucy** [comment]
> I encountered same issue with binance pool and now with ethermine, gtx1660ti on laptop, rtx3060ti and 2070, press ctrl-c one time and all the missing console messages will appear...

Hey, thanks! I appreciate it! Ill check if it works tomorrow

**Comment by BigGayLucy** [comment]
It works great. Thank you. I checked it out today
