### ISSUE TITLE
Miner Looks stuck and isn't finding jobs for ethash

### ISSUE THREAD

**Issue by aliamir51** [develsoftware/GMinerRelease#169]
Hello, I am have been using the gminer for a while now to mine eth occasionally on my PC (NVIDIA RTX 2070 Super) on the binance pool, and it was working fine. Lately, the miner is acting weird. Sometimes It crashes and gives me pop up that miner.exe has stopped working. Then I noticed that even when it runs without the pop up it detects the GPU and then gets stuck and doesn't find any jobs.  The bellow is what the miner shows and nothing after that for more than hours:

"19:10:27 Connected to ethash.poolbinance.com:8888   
19:10:27 Authorized on Stratum Server 
19:10:27 New Job: 83dc16b0 Difficulty: 2.14G  
19:10:27 Started Mining on GPU0: ZOTAC GeForce RTX 2070 SUPER 8GB [0000:01:00.0] "

I thought it had something with cmd when you press on it kinda pauses, but it isn't the case I pressed enter with no result.
I tried other pools for eth same problem. It works for other algorithms. I did try the latest release.
Any help is really appreciated.

**Comment by thaneb** [comment]
I do not have any issue with my 2070 on others pools, but there is sure a big problem on binance eth pool.
Their latency is just totally crazy since few days/week, making their pool just unusable (I saw 22200ms to validate a shares, when ethermine takes 81ms).
But it should not explain you issue.
Did you manage to exclude your mining software folder from defender/anti virus watch? (I would thing about this kind of issue at first)

**Comment by aliamir51** [comment]
I did exclude the miner and the folder from defender/anti-virus watch . The problem for me is also on determine. I don't know what changed. As I said I also tried updating to the latest version I was using version 2.41 and after facing the issue I am now using 2.47.

**Comment by aliamir51** [comment]
The issue was solved. The problem was solved by doing a restore for windows 10 for the last restore point (2 days ago ) and the affected programs were nvidia driver and another game I installed. So I am guessing this has to do with the latest nvidia drivers. Maybe if someone updated the nvidia drivers could confirm if this happened to them. Thank you @thaneb for your response.
