### ISSUE TITLE
kernel parameter does not apply

### ISSUE THREAD

**Issue by kolba** [develsoftware/GMinerRelease#186]
I've tried applying a specific kernel via a config, `--kernel` or `-k` and none of those have any effect. seems to be defaulting to auto kernel selection (seems to favor kernel 4 or 6). single GPU, RTX 3080, windows

**Comment by pdieppa** [comment]
I wonder if the version you are trying to select is not compatible with the RTX 3080.

**Comment by kolba** [comment]
fixed in 2.50

thanks
