### ISSUE TITLE
2.49 POWER AND EFFICIENCY SHOWS N/A

### ISSUE THREAD

**Issue by a7dfj8aerj** [develsoftware/GMinerRelease#187]
Version 2.49 has error of power reading.
2.47 works fine

**Comment by grusio** [comment]
I have the same problem.

**Comment by L0ngMarch** [comment]
same problem on asus 3060mobile

**Comment by Weasel163** [comment]
same problem. 2.47 - OK, but since 2.48 and in 2.49 - N\A for power and efficiency.

**Comment by kolba** [comment]
works ok for me in 2.50 on windows

**Comment by Weasel163** [comment]
it doesn't work for me in 2.50 on windows :(

**Comment by grusio** [comment]
for me is working :-)

**Comment by a7dfj8aerj** [comment]
2.50 Works for me with efficiency and power readings.
