### ISSUE TITLE
Workers ID not working v2.50

### ISSUE THREAD

**Issue by BillC58** [develsoftware/GMinerRelease#192]
All workers are named eth1_0, notwithstanding the worker ID used in the batch file.

**Comment by Thyrador** [comment]
Use the new --worker-parameter as per changelog:
```-u 0xMINERADRESS.YourWorkerName --worker YourWorkerName```

**Comment by kolba** [comment]
it didn't pick it up from the config, but does work with `--worker` parameter passed to the executable

**Comment by Thyrador** [comment]
```
[server]
host=YOUPOOLID
port=YOURPOOLPORT
user=0xMINERADRESS
proto=stratum
worker=YourWorkerName
```

This should work @kolba

I'm using this approach in my config and it displays the worker name.

**Comment by BillC58** [comment]
Yes. It works fine with --worker.

**Comment by kolba** [comment]
@Thyrador i've been putting it into `[common]` so maybe that's why it didn't pick it up for me
