### ISSUE TITLE
Worker name doesnt work

### ISSUE THREAD

**Issue by pakosanz** [develsoftware/GMinerRelease#194]
i put a worker name after my wallet but its not reflected on the pool

**Comment by longdds** [comment]
I can't set the worker name also.

**Comment by affifymirza** [comment]
same issue. need to revert back to v2.49 to get worker name work on the pool. hopefully dev fix this issue.

**Comment by affifymirza** [comment]
You can fix by manually add --worker **RIG_NAME**

**Comment by shackrock** [comment]
Same for me in 5.0 - defaults to eth1_0 for all workers using old commands now.

**Comment by shackrock** [comment]
> You can fix by manually add --worker **RIG_NAME**

Can confirm this corrects the behavior in v5.0.

**Comment by pakosanz** [comment]
--worker does the charm, thanks
