### ISSUE TITLE
Miner slows down after any game played.

### ISSUE THREAD

**Issue by JoshuaShelswell** [develsoftware/GMinerRelease#195]
Miner slows down 2/3's after any game is played and i restart the miner. Hardware is a 2080 Super running on windows 10. Have to restart computer every time i want to turn the miner back on, hope this helps, thanks.

**Comment by DjavanRoa** [comment]
Can you confirm GPU OC is the same before and after having played the game ?
You probably should try forcing OC values using params --cclock  --mclock and --pl on command line so it's reapplied each time you start the miner.

**Comment by JoshuaShelswell** [comment]
> 
> 
> Can you confirm GPU OC is the same before and after having played the game ?
> You probably should try forcing OC values using params --cclock --mclock and --pl on command line so it's reapplied each time you start the miner.

i fopund out what was wrong, it was the new nvidia drivers i used these and now everything works perfectly, you should post an update as to what specific drivers to use because of incompatibilities,  this is the driver i m,anaged to find and ended up using

the OC values unfortunatly have nothing to do with it, its been working fine for months before all these recent windows and nvidia updates, after a fresh format i installed current nvidia drivers and had nothing but the exact same issues but worse until i found this driver, now everythings good, hope you figure out how to get this info to others as it was the solution to the days worth of issues i was having, ill also post the link to the driver for you, thank you for the help, and as far as i knew in your readme you can only apply those values to amd gpu's not nvidias, i use the performance overlay to undervolt my gpu and i dont touch clock or memory speeds, runs almost 10gh @ 170w on my 2080 super

https://www.reddit.com/r/gpumining/comments/m5so68/nvidia_driver_47005_download_link/
