### ISSUE TITLE
v2.50: cuckoo29@nicehash not working with GTX1660

### ISSUE THREAD

**Issue by UselessGuru** [develsoftware/GMinerRelease#199]
GTX1660 6GB

Command line used
`miner.exe --algo cuckoo29 --server CUCKOOCYCLE.eu-west.nicehash.com:3376 --user *******************************.******* --pass x --mt 2 --api 4003 --watchdog 0`

v2.49 works fine.

**Comment by develsoftware** [comment]
Please take look to 2.51 beta, it’s should works fine

**Comment by UselessGuru** [comment]
> look to 2.51 beta, it’s should works fine

Works. Thank you.
