### ISSUE TITLE
Feature request: make --fan set initial fan speed when --tfan is also active.

### ISSUE THREAD

**Issue by igoralebar** [develsoftware/GMinerRelease#204]
It takes a few minutes for fans to ramp up and down with --tfan option until stable temperature is reached.
Would be nice to be able to set initial fan speed with unused --fan option, or a separate option, so stable temperature state could be reached faster and with less thermal cycling during initial fan adjustment. Thanks!

**Comment by develsoftware** [comment]
use --tfan_min for this purpose

**Comment by igoralebar** [comment]
> use --tfan_min for this purpose

oh, nice, I missed that when looking through --help, thank you !
