### ISSUE TITLE
--kernel parameter for Nvidia only?

### ISSUE THREAD

**Issue by DeeDeeRanged** [develsoftware/GMinerRelease#207]
I like to know if --kernel parameter is only for Nvidia cards or also for AMD cards?

**Comment by igoralebar** [comment]
--kernel' or shortly '-k' - space-separated list of kernel numbers for each device (0 - auto, 1-6 - kernel number, currently supports 6 kernels for Nvidia on Ethash/Etchash), default value is 0 (for example: '1 3 5')

**Comment by DeeDeeRanged** [comment]
I must have been blind, thks for pointing it out :D
