### ISSUE TITLE
Gminer hangs at startup - sometimes (since at least v1.45, probably since v1.35)

### ISSUE THREAD

**Issue by RainbowMiner** [develsoftware/GMinerRelease#21]
Sometimes Gminer just stops at the startup and hangs (almost) idle. It looks like it tries to calculate something on the GPUs (MSI Afterburner shows active memory and core clock), but the temperature remains low.

This is what you get:
```
+----------------------------------------------------------------+
|                          GMiner v1.47                          |
+----------------------------------------------------------------+
Algorithm:          Equihash + Scrypt "VDS"
Stratum server:     
  host:             stratum://vds-eu.uupool.cn:13032
  user:             
  password:         x
Power calculator:   on
Color output:       on
Watchdog:           off
API:                http://127.0.0.1:32900
Log to file:        off
Selected devices:   GPU0
Intensity:          100 
Temperature limits: 90C 
------------------------------------------------------------------
```
(user address removed)

Then, the miner just waits forever and you need to Ctrl+C or kill it.

This is what I have tried:
- enabling watchdog did not help
- disabling power calculator did not help
- lower overclocking frequencies did not help
- start with/without admin privileges did not change a thing
- it happens for all algorithms
- no matter if only one GPU or multiple GPUs are in use.
- If I enable logfiles, the log file is being created, but remains empty.
- it happens more often, if you start miner.exe as subprocess (e.g. if using powershell's "Start-Process" command)
- gminer is the only miner, out of a bunch of others, that behaves like that
- **now comes the weird thing:** if miner.exe fails as subprocess in powershell and *does not* fail, when called by hand in a cmd window (using the exact same command line arguments), it then does not fail anymore when called as subprocess in powershell, afterwards.

Any idea, what is happening? Please fix this. Also, if you need assistance in debugging, please let me know.

**Comment by psynauty** [comment]
With any version beyond 1.34 with 12 GPUs the whole system hard reboots on Linux. Why???
Windows is a mess of its own but nothing to do with the miner

**Comment by RainbowMiner** [comment]
This hang still happens with the newest release. Since it happens erratically, I wonder, if it is a connection problem to some gminer owned server?
@develsoftware is gminer trying to connect to somewhere at the start?

**Comment by RainbowMiner** [comment]
@develsoftware same issue with new version 1.52 - it is selective. I had it running on a system with different gpu models. On some it started on others, it hang again.

**Comment by RainbowMiner** [comment]
Never had this problem again with gminer v1.7x
