### ISSUE TITLE
2.52 big problem with disable P2 state

### ISSUE THREAD

**Issue by devour7** [develsoftware/GMinerRelease#215]
when i use [--p2state 0] for eth,minner become very instable,and then I couldn't reopen P2 state(I tried use -[-p2state 1];or go back to 2.51;it's still running at P0 mode) ,what should I do?

**Comment by igoralebar** [comment]
do you understand what P2 mode does and why people disable it?
if so, then you should be aware that your memory speed during mining is at P0 levels, so you need to adjust your memory overclocks

**Comment by devour7** [comment]
> do you understand what P2 mode does and why people disable it?
> if so, then you should be aware that your memory speed during mining is at P0 levels, so you need to adjust your memory overclocks

I knew, do your? why I disable it if I don't know what it does? 
 I did adjust memory much lower then before,hashrate was less,but invalid share was up.  
what I want asked is how to reopen P2 state.

**Comment by igoralebar** [comment]
what do you mean by reopen?

you can enable/disable "force p2 state" back with nvidia profile inspector, just like you always could without gminer
