### ISSUE TITLE
Target temperature option with Fan control (not --templimit)

### ISSUE THREAD

**Issue by singsonn** [develsoftware/GMinerRelease#217]
I would like to have an option to setup a target temperature for the GPU. When the target temperature is set, gminer will control the GPU fans to stay at the target temperature.

Much like the -tt option with phoenix miner :

```
-tt <n>
Set fan control target temperature (special values: 0 - no fan control, negative - fixed fan speed at n %)
```

Currently, I only see the `--templimit` option that is stopping mining operations once the temperature defined in that option is reached, which is nothing like phoenix miner `-tt` option.

**Comment by igoralebar** [comment]
read the manual (i.e. --help) gminer already has it

**Comment by singsonn** [comment]
Got it, didn't see the `--tfan` option in the project README, didn't think to check the `--help` option either.

Thanks, we can close this issue.
