### ISSUE TITLE
GMiner can't work fine with ezil pool.

### ISSUE THREAD

**Issue by chuz** [develsoftware/GMinerRelease#218]
This is the log. When zil active in ezil pool, new DAG file loading fail?
![image](https://user-images.githubusercontent.com/2840119/115257419-a6120d80-a162-11eb-87c9-c76de1f1a076.png)

**Comment by chuz** [comment]
Device is R9000P RTX3060

**Comment by igoralebar** [comment]
Have same issue from time to time, but it goes away after a couple restarts by watchdog, and uses cached DAGs properly on the next transitions from zil->eth and eth->zil. That's why I set my watchdog timeout to 0.

**Comment by chuz** [comment]
> Have same issue from time to time when initially starting the miner before both DAGs are cached. But it goes away after a couple restarts by watchdog, and uses cached DAGs properly on the next transitions from zil->eth and eth->zil. That's why I set my watchdog timeout to 0.
> Hopefully there will be a proper fix for this.

The DAGs are not cached on the same time. My issue is that when the GM switches from ETH to ZIL, the GM clears the DAG from the graphics card and loads the DAG from ZIL, and then GM report an bug and watch dog auto restart GM. Log as shown above.

**Comment by typekx** [comment]
This is not a problem. U overclock your laptop outer program ( i think MSI afterburner) , dag checks sometimes, if you overclock from gminer problem wilk be disolved.
