### ISSUE TITLE
no device found (ubuntu 16.04)

### ISSUE THREAD

**Issue by zhangyuan1997** [develsoftware/GMinerRelease#225]
I have 4*GTX 1080Ti on my computer, which system version is ubuntu 16.04 and gminer version is 2.51. When I simply run mine_eth.sh, the terminal shows 'no device found'. What can I do about that? Thanks a lot!
![QQ截图20210421162956](https://user-images.githubusercontent.com/30192850/115523278-7f1d1e00-a2bf-11eb-92cc-b23505c0166e.png)
![QQ截图20210421163010](https://user-images.githubusercontent.com/30192850/115523302-83493b80-a2bf-11eb-9984-8b02f8c2917b.png)

**Comment by ahmedselim2017** [comment]
Hi, unfortunatly I get the same error. How did you solve it?

**Comment by BrightXiaoHan** [comment]
same question
