### ISSUE TITLE
Version 2.53 proto not specified for server 2

### ISSUE THREAD

**Issue by borgdrone7** [develsoftware/GMinerRelease#227]
Hi,
I updated to the latest HiveOs and I am getting error that proto is not specified for server 2. The new Gminer version is 2.53, old one is 2.47. The same settings work on old one. Also, what is meant by server 2? 
Thanks

**Comment by igoralebar** [comment]
do you have failover servers specified?
even if it's a bug, I would set one more --proto in the end of config, just in case

**Comment by borgdrone7** [comment]
Hi, thanks for a quick reply. Yes, there are 3 servers specified in config and '--proto stratum' once. So you are saying I can just add twice more '--proto stratum' and  it should be ok?

**Comment by igoralebar** [comment]
yes, if you specified --proto for one server, specify it for the rest as well

**Comment by borgdrone7** [comment]
that worked, thanks a mil!
