### ISSUE TITLE
"Anti-hacking system detected" when started from Node.js

### ISSUE THREAD

**Issue by o2genum** [develsoftware/GMinerRelease#23]
GMiner refuses to start when run by Node.js, emitting "Anti-hacking system detected". This is similar to bugs #12, #6. This prevents the miner from being integrated into mining solutions.

`node run.js`

run.js:
```
const { exec } = require("child_process")

exec('miner.exe --api 8888 --algo 150_5 --server beam-eu.leafpool.com --port 3333 --ssl 1 --user 18bdda8a95fa392e58ba67c72d642086715a8d0fc0fc4519442d77bddef9e3045c4.worker0 --logFile log.txt')
```

**Comment by R00dNet** [comment]
i am too getting this error. exe has all the permissions it needs.

**Comment by fegauthier** [comment]
I have the same problem too. I use the spawn command. The miner work well without NodeJS, but when I want to integrate it into my mining solution, I get this error...

**Comment by UselessGuru** [comment]
Same happens when started from a powershell script within Visual Studio Code.

**Comment by fegauthier** [comment]
I hope that the developers will fix this problem soon...

A workaround would be to add a Scheduled Task that run the miner and in your code you can start/stop the schedule task...

**Comment by R00dNet** [comment]
this error is still present in latest release... can the dev give some insight as to why this is happening? I have given the exe all the permissions it needs and excluded from comodo security features... there is literally nothing left to give the exe access to, yet this error persists

**Comment by fegauthier** [comment]
I have the impression that developers don't tracks issue on GitHub or at least they don't care... I think we will wait for a long time....

**Comment by develsoftware** [comment]
someone with this issue please contact me in telegram @evgeniy_pochitaev, I'll send test build

**Comment by R00dNet** [comment]
which telegram group? i have joined https://t.me/gminer_equihash yet cannot chat or see members...

**Comment by develsoftware** [comment]
You can reach me in beta test group t.me/gminer_beta

**Comment by fegauthier** [comment]
@develsoftware add an exception for NodeJS and it works with the build that he send me. He will include the fix in the next release. Thank you!

**Comment by R00dNet** [comment]
anti hacking error is presented at "check 7". nodejs, like gminer, has all the permissions to run.

miner.exe --algo 125_4 --server zel-eu.coinblockers.com --port 4446 --user .... --pass x --devices 1 --intensity 60

any help is greatly appreciated...

**Comment by R00dNet** [comment]
Users who use comodo have to turn off "apply the selected action to unrecognised autorun entries related to new/modified registry items" in advanced protection - miscellaneous

**Comment by develsoftware** [comment]
fixed in GMiner v1.52

**Comment by KnightZhao** [comment]
I tried 1.52, or not. I use python to start gminer

**Comment by interbiznw** [comment]
Can you add electron as an exception to start the miner?

**Comment by dsarfati** [comment]
We are also getting the same exception when trying to run GMiner from a C# application. Any help would be greatly appreciated, have have a few hundred users waiting on a fix.

**Comment by fegauthier** [comment]
> We are also getting the same exception when trying to run GMiner from a C# application. Any help would be greatly appreciated, have have a few thousand users waiting on a fix.

You will have to ask the dev to add an exception in the code like they did for NodeJS

**Comment by dsarfati** [comment]
@develsoftware What do we need to do to get an exception added. I even tried running it from a `.bat` file and still no luck. Like I said, we have thousands of users that run our application and we would like to move them from ethminer to GMiner but are unable to because of this error.

**Comment by stonetrek** [comment]
@develsoftware I was in the test group t.m /gminer_beta, I sent a message, no one replied.

**Comment by jinfagang** [comment]
Same error:


```
+----------------------------------------------------------------+
|                          GMiner v2.45                          |
+----------------------------------------------------------------+
Algorithm:          Ethash
DevFee:             0.65%
Stratum server:     
  host:             eth.2miners.com:2020
  user:             0x90AcA10AD238e54F727add281Db1cF2E7a09
  password:         x
Power calculator:   on
Color output:       on
Watchdog:           on
API:                off
Log to file:        off
Selected devices:   GPU0
Intensity:          100 
Temperature limits: 90C 
------------------------------------------------------------------
21:31:12 Anti-hacking system detected modification of the miner memory. If you using an antivirus, add miner to antivirus exceptions
21:31:12 Miner terminated, watchdog will restart process after 10 seconds

```
