### ISSUE TITLE
What is meaning of `--proto` option?

### ISSUE THREAD

**Issue by clever-cerf** [develsoftware/GMinerRelease#237]
I don't quite understand the meaning of `--proto`. When to specify `proxy`? and when to specify `stratum`?

Can you explain it? Thank you!

**Comment by pdieppa** [comment]
That depends on the pool. Usually you can find instructions at the pool on how to connect. If you don't know which protocol the pool uses, you can skip it and I believe the miner will automatically test for the correct one.

**Comment by clever-cerf** [comment]
OK. Thank you very much!
