### ISSUE TITLE
Nvidia RTX 2060 Problem when trying to set --cclock --mclock --lock_voltage Help needed

### ISSUE THREAD

**Issue by gminadak** [develsoftware/GMinerRelease#238]
Hello and thank you for this software.

First of all i want to mention that i try to use the CLI overclock method becouse if the error occurs the MSI afterburner resets my card to default settings for some reason and my card (GeForce RTX 2060 VENTUS 6G OC) starts over heating as expected.
So i want to run it from CLI becouse that way the settings forced by the CLI and my card continues to mine as expected without problems.

So here is what happens, when i try to run my overclock settings from CLI i get the following error sometimes after a while (3-6 hours) and other times almost instantly and repeatedly.

```
2021-04-27 14:15:16 Error on GPU0: unknown error
2021-04-27 14:15:16 GPU0: Fan speed changed to default
2021-04-27 14:15:16 Stopped Mining on GPU0
2021-04-27 14:15:17 Miner terminated, watchdog will restart process after 10 seconds
```

With the exact same setting's from MSI afterburner I don't get this error (maybe i see the error 1 time over 13-14 hours or don't see it at all until i decide to reboot my PC).
I realy can't understand why this happens while in both cases i have the exact same settings.

Every time i use the CLI overclock method i have MSI afterburner closed and runing the miner.exe program as Administrator always.
I'm including some pictures of my settings and the CLI parameters for both cases.
I have try both 2.52 and 2.53 version.

`miner.exe --algo ethash --kernel 6 --tfan 45 --tfan_min 50 --tfan_max 80 --templimit 60 --electricity_cost 0.11 --server ethash.poolbinance.com:1800 --user ********** --log_date 1 --logfile C:\gminer_2_52\miner.log --api 192.168.1.10:12000`

`miner.exe --algo ethash --cclock -380 --mclock 870 --lock_voltage 756 --kernel 6 --tfan 45 --tfan_min 50 --tfan_max 80 --templimit 60 --electricity_cost 0.11 --server ethash.poolbinance.com:1800 --user ********** --log_date 1 --logfile C:\gminer_2_52\miner.log --api 192.168.1.10:12000`

![with_msi_afterburner](https://user-images.githubusercontent.com/45330594/116318857-4b803f00-a76a-11eb-86ff-0a8b6e850f68.PNG)

![curve](https://user-images.githubusercontent.com/45330594/116318852-49b67b80-a76a-11eb-92f3-1edf0ea07dd5.PNG)

**Comment by Yulining0** [comment]
Some with you. My card is GTX 1060 6g. It always reset my card to default setting. My afterburner actually is usable.

**Comment by Yulining0** [comment]
Hope developer could add a parameter to turn on or off the function reset our card which is perfect for this excellence software.
