### ISSUE TITLE
nvml.dll is eiher not designed to run with Windows or it contains an error

### ISSUE THREAD

**Issue by rashisan** [develsoftware/GMinerRelease#24]
Hello,

i am trying to run gminer 1.50 with the latest Nvidia driver 430.86 win10-64bit whql but this error appears at the screen "nvml.dll is eiher not designed to run with Windows or it contains an error".
I have four Nvidia 1080TI 11GB cards.

Could you please assist.

![gminer1 50error](https://user-images.githubusercontent.com/1037761/60702777-8adffa80-9f08-11e9-8942-120f74549f3a.png)

**Comment by develsoftware** [comment]
added option --nvml 0 to disable NVML
