### ISSUE TITLE
NVML.dll is in System32 folder on newer drivers

### ISSUE THREAD

**Issue by o2genum** [develsoftware/GMinerRelease#26]
The miner currently doesn't work on RTX 2060 without additional manipulations.

[The explanation.](https://forums.geforce.com/default/topic/1100164/nvml-dll-and-nvsmi-folder-missing/)

For RTX 2060 and Windows 10, NVIDIA driver is installed automatically (DCH driver).

This driver installs NVML.DLL to System32, not to NVSMI. You should look for the DLL in System32, too.

**Comment by develsoftware** [comment]
fixed in GMiner v1.51
