### ISSUE TITLE
Anti-hacking system detected error in windows 11 build 21996.1

### ISSUE THREAD

**Issue by gokulramtj** [develsoftware/GMinerRelease#285]
Miner fails to run throwing an error "Anti-hacking system detected modification of the miner memory. If you using an antivirus, add miner to antivirus exceptions" for Equihash 144,5 "BgoldPoW"  algorithm even though the miner has been added to exception in antivirus.

**Comment by develsoftware** [comment]
Hello, please contact me in telegram @evgeniy_pochitaev I will try to help you

**Comment by gokulramtj** [comment]
Thanks, Fixed with version 2.59
