### ISSUE TITLE
Error after installing latest AMD driver 21.6.1

### ISSUE THREAD

**Issue by tomrus88** [develsoftware/GMinerRelease#290]
Version: v2.57

Command line
`miner.exe -a ethash --proto stratum --server SERVER -u USER -d 0 -w 0 --api 4000`

Error message says:
`LLVM ERROR: Error while trying to spill SGPR4_SGPR5 from class SReg_64: Cannot scavenge register without an emergency spill slot!`

**Comment by vatch2** [comment]
same

**Comment by vatch2** [comment]
fixed in 2.58
