### ISSUE TITLE
Crashes after install of latest AMD driver 27.20.22001.14011

### ISSUE THREAD

**Issue by CaptnFabulous** [develsoftware/GMinerRelease#291]
Tried latest version 2.57 and older version 2.47. No error message other than "Miner terminated, watchdog will restart process after 10 seconds", which comes up immediately after posting the driver version.

**Comment by iga2iga** [comment]
Same, 5700xt drv 2.6.1, older driver works.

**Comment by vatch2** [comment]
same

**Comment by vatch2** [comment]
fixed in 2.58

**Comment by CaptnFabulous** [comment]
Confirmed fixed for me.

> fixed in 2.58
