### ISSUE TITLE
Add feature to control display info

### ISSUE THREAD

**Issue by gwongis88** [develsoftware/GMinerRelease#292]
Can you please add feature to control how often to display the device shares info? Such as every minute or X seconds instead of every 30 seconds?

**Comment by develsoftware** [comment]
We already have this option --report_interval seconds

**Comment by gwongis88** [comment]
Great Thank.  Hmmm.  I couldn't find that parameter from the Read Me Text even with the latest 2.57 download.  Now I am wondering what other option I have been missing..

**Comment by gwongis88** [comment]
If possible, please send me a link for all the parameters.  Thanks

**Comment by igoralebar** [comment]
`miner.exe --help`
scroll down
