### ISSUE TITLE
High cpu usage with nvidia driver 471.11 and 471.22

### ISSUE THREAD

**Issue by girtsjj** [develsoftware/GMinerRelease#307]
I am experiencing high cpu usage with both newest drivers from nvidia. It hovers around 80% instead of idling like normal. That gives me extra 80W power consumption.
Another issue with these drivers is that it changes the set fixed core clock and memory clock by around 8mhz. I have 3x 3080 and 2x 3070. They all have shifted their clocks same way. I am using gminer with minerstat. All OC settings done with miner.
Both issues go away if I revert to previous 466.77 driver version. 
Something has changed in new driver and it is not playing well with the miner. Normally I would just stay on the driver that works but I play games too. New driver enables RTX on doom Eternal which I would like to use.

**Comment by rollindea** [comment]
I have the same problem, 50% cpu instead of 1%

**Comment by girtsjj** [comment]
> I have the same problem, 50% cpu instead of 1%

Good to know I am not alone. Devs? A fix please?

**Comment by sibada1986** [comment]
I have the same problem too, and I found that this problem was introduced in 2.51.

**Comment by girtsjj** [comment]
Several gminer and nvidia driver versions later and still no fix.. Are devs reading the issues reported by users at all?

**Comment by rollindea** [comment]
Did any of you that are having this issue try an uptodate gminer with a new nvidia driver? is the problem fixed?

**Comment by fabriciofreitag** [comment]
With gminer and nvidia drivers on the latest version it still happens.
I had to downgrade Nvidia to 390, and turn **on** hardware acceleration on all apps that allow it (sublime, chrome, etc) to fix it.
Though some specific apps still seem to cause it.

**Comment by girtsjj** [comment]
> Did any of you that are having this issue try an uptodate gminer with a new nvidia driver? is the problem fixed?

Problem still persists. As soon as there is a new gminer version out I get it hoping the issue is solved. Then update last good working drivers (466.77) to newest and test.

**Comment by girtsjj** [comment]
Not sure what did it. I had 5 cards on my windows PC. Built a rig and left only 3090 on my PC. Now with gminer 2.68 and newest driver 471.96 cpu usage is fixed. Closing the issue.
