### ISSUE TITLE
gminer_2_65_windows64.zip Windows Security/Defender found Wacapew.C!ml

### ISSUE THREAD

**Issue by jdromero88** [develsoftware/GMinerRelease#344]
![Screenshot 2021-08-19 111928_LI](https://user-images.githubusercontent.com/51330062/130098175-8a8a4186-967f-4d7a-8984-8f55ccf0a59a.jpg)

**Comment by pdieppa** [comment]
All miner programs are detected and block and most anti-virus programs.
You have to create exceptions in the AV program to allow the download and running of the miners.
