### ISSUE TITLE
GMINER_V2.65 power consumption

### ISSUE THREAD

**Issue by andre22251** [develsoftware/GMinerRelease#345]
Hi, since the update to v2.65 (vs 2.64), I have 2-3W more consumption per GPU. Any performance improvement? Thanks.

**Comment by omega180984** [comment]
Hello,
did you check your powersuply or powerlimits. My couple of rigs (all NVIDIA 3000series cards) have no change in power consumption.

**Comment by andre22251** [comment]
Yes. It could be some power setting. I will check it. Thanks for support. Good work.
