### ISSUE TITLE
lock_cclock not working (admin privileges)

### ISSUE THREAD

**Issue by starwatcher11** [develsoftware/GMinerRelease#350]
Hello.
I'm using GMiner **v2.65** on a Windows 10 20H2 PC with my **Gigabyte GTX 1050 Ti Windforce OC 4G** for kawpow-ravencoin mining. Game-Ready driver version **471.41** (**non-DCH**).
I want to underclock my GPU to 1500MHz but I can't do that using the --lock_cclock 1500. It shows me the following error:
`GPU0: Failed to change locked core clock point to 1500 MHz, run miner with admin privileges`
However, I have already set the miner.exe to always run with admin privileges.

I used the following command using a ravencoin.bat file and run it WITH ADMIN PRIVILEGES:
`miner.exe" --algo kawpow --server server.server:11111 --user addr.workerName --lock_cclock 1500 --mclock 700 --pl 65 --p2state 0 --fan 63`

I tried without power limit but still shows same error.
I don't know if this is a bug with the miner or my fault, I could really use some help.

**Comment by DeeDeeRanged** [comment]
Just a crazy idea to try.
`miner.exe" --lock_cclock 1500 --mclock 700 --pl 65 --p2state 0 --fan 63 --algo kawpow --server server.server:11111 --user addr.workerName`
Don't know if the order makes any difference with SRBminer-MULTI it does.

**Comment by starwatcher11** [comment]
> 
> 
> Just a crazy idea to try.
> `miner.exe" --opencl 0 --lock_cclock 1500 --mclock 700 --pl 65 --p2state 0 --fan 63 --algo kawpow --server server.server:11111 --user addr.workerName`
> Don't know if the order makes any difference with SRBminer-MULTI it does.
> Can you actually mine ravencoin with a 4GB vram card?
> Run it from an command prompt with admin rights and see what happens.

Still no luck, it doesn't work. Yes, mining ravencoin is still possible with 4GB vram, at least for a while.

**Comment by DeeDeeRanged** [comment]
Take it you have tried it with other miners like xmrig or whatever to see if it works?

**Comment by starwatcher11** [comment]
> 
> 
> Take it you have tried it with other miners like xmrig or whatever to see if it works?

No I haven't. I'll try it but to be honest I prefer to use GMiner cause of the best performance it offers

**Comment by igoralebar** [comment]
You can't lock core clocks on Pascal GPUs, only Turing and up

**Comment by starwatcher11** [comment]
> 
> 
> You can't lock at specific core clocks on Pascal GPUs, only Turing and up

sorry, didn't know that, I though I could. If only the miner's readme was more specific. thanks anyway.

**Comment by igoralebar** [comment]
I think it's because the issue is with Pascal cards themselves, they don't have that function in them, you can only lock voltage and set frequency offsets, the resulting frequency will depend on power and thermal limits.
