### ISSUE TITLE
2.67: driver 470.63.01 installed . 2 3060ti not detected. 2.66 works.

### ISSUE THREAD

**Issue by elestranobaron** [develsoftware/GMinerRelease#371]

**Comment by elestranobaron** [comment]
No problem anymore with 2.68 even with driver 460.73.01

**Comment by lollos73** [comment]
can't mine cortex i just try the example bat file and this is result

+----------------------------------------------------------------+
|                          GMiner v2.68                          |
+----------------------------------------------------------------+
Algorithm:          Cortex
DevFee:             5 %
Stratum server:     
  host:             ctxc.2miners.com:2222
  user:             0x321ae4016a6397ee004b3f5f9e6c0a0c1915a05d
  password:         x
Power calculator:   on
Color output:       on
Watchdog:           on
API:                off
Log to file:        M:\Miner\gminer_2_68_windows64\log.txt
Selected devices:   GPU0  
Intensity:          100   
Temperature limits: 90/120
------------------------------------------------------------------
17:05:52 Nvidia Driver: 466.77
17:05:53 Failed to initialize miner on GPU0: ZOTAC NVIDIA GeForce RTX 3070 Ti 8GB [0000:26:00.0]: out of memory
17:05:53 No devices for mining
