### ISSUE TITLE
100% fan speed on secondary psu

### ISSUE THREAD

**Issue by elestranobaron** [develsoftware/GMinerRelease#372]
Hi Don't know if this is miner related or not.

Got one psu 1600w and another 800w

GPU on first PSU are running all right but on second fan speed is always 100%. Any idea ? risers and sata connected on same

**Comment by Quilium** [comment]
Maybe you can set the optional parameters fan parameters when starting gminer.
These parameters should control the fan speed.

**Comment by elestranobaron** [comment]
I'm on Linux. But strange fact iss all gpu connected on first power supply are 3070. fans between 30 70 %

Second power supply 2 3080 and one 3090 always at  100 % 97 % 100%

**Comment by elestranobaron** [comment]
What i dont get is in half an hour i pass from this 

+---+-----+----+-----+-----------+------+----+-----+-------+-------------+
| ID  GPU  Temp  Fan     Speed    Shares Core  Mem   Power   Efficiency  |
+---+-----+----+-----+-----------+------+----+-----+-------+-------------+
|  0  3080   56 100 %  86.87 MH/s  3/0/0  930  9251   217 W  400.35 KH/W |
|  1  3090   61 100 % 100.07 MH/s  7/0/0  870  9501   288 W  347.45 KH/W |
|  2  3070   63  32 %  52.06 MH/s  1/0/0 1935  6800   198 W  262.92 KH/W |
|  3  3070   58  33 %  52.06 MH/s  1/0/0 1965  6800   195 W  266.96 KH/W |
|  4  3080   63 100 %  87.26 MH/s  2/0/0 1905  9251   335 W  260.47 KH/W |
|  5  3070   66  42 %  52.06 MH/s  0/0/0 1965  6800   201 W  258.98 KH/W |
|  6  3070   67  67 %  52.06 MH/s  3/0/0 1920  6800   195 W  266.96 KH/W |
|  7  3070   71  79 %  52.06 MH/s  2/0/0 1920  6800   187 W  278.38 KH/W |
|                     534.48 MH/s 19/0/0             1816 W  294.32 KH/W |
+---+-----+----+-----+-----------+------+----+-----+-------+-------------+
22:15:00 Pool: eth.f2pool.com:6688 Shares/Minute: 3.80
22:15:00 Pool Hashrate: 544.03 MH/s Efficiency: 101.79 %
22:15:00 Uptime: 0d 00:05:00 Electricity: 0.149 kWh


to that

+---+-----+----+-----+-----------+------+----+-----+-------+-------------+
| ID  GPU  Temp  Fan     Speed    Shares Core  Mem   Power   Efficiency  |
+---+-----+----+-----+-----------+------+----+-----+-------+-------------+
|  0  3080   56 100 %  86.87 MH/s  3/0/0  930  9251   217 W  400.35 KH/W |
|  1  3090   61 100 % 100.07 MH/s  7/0/0  870  9501   288 W  347.45 KH/W |
|  2  3070   63  32 %  52.06 MH/s  1/0/0 1935  6800   198 W  262.92 KH/W |
|  3  3070   58  33 %  52.06 MH/s  1/0/0 1965  6800   195 W  266.96 KH/W |
|  4  3080   63 100 %  87.26 MH/s  2/0/0 1905  9251   335 W  260.47 KH/W |
|  5  3070   66  42 %  52.06 MH/s  0/0/0 1965  6800   201 W  258.98 KH/W |
|  6  3070   67  67 %  52.06 MH/s  3/0/0 1920  6800   195 W  266.96 KH/W |
|  7  3070   71  79 %  52.06 MH/s  2/0/0 1920  6800   187 W  278.38 KH/W |
|                     534.48 MH/s 19/0/0             1816 W  294.32 KH/W |
+---+-----+----+-----+-----------+------+----+-----+-------+-------------+
22:15:00 Pool: eth.f2pool.com:6688 Shares/Minute: 3.80
22:15:00 Pool Hashrate: 544.03 MH/s Efficiency: 101.79 %
22:15:00 Uptime: 0d 00:05:00 Electricity: 0.149 kWh

I know both 3080 and 3090 are connected on a 800W PSU

And the five 3070 on the 1600W PSU

But i tried to switch

it seems the two always decrease over time. Is it because of the heat ?  still dont know

**Comment by elestranobaron** [comment]
Now i have only one 3080 and one 3090 on CORSAIR PSU 800 W instead of 2 3080 and ONE 3090
Other have 5 3070 plus 1 3080

+---+-----+----+-----+-----------+--------+----+-----+-------+-------------+
| ID  GPU  Temp  Fan     Speed     Shares  Core  Mem   Power   Efficiency  |
+---+-----+----+-----+-----------+--------+----+-----+-------+-------------+
|  0  3080   57  98 %  83.20 MH/s   17/0/0  870  9251   212 W  392.44 KH/W |
|  1  3090   62 100 %  91.57 MH/s   24/0/0  810  9501   246 W  372.24 KH/W |
|  2  3070   64  34 %  52.06 MH/s   11/0/0 1920  6800   201 W  259.00 KH/W |
|  3  3070   58  35 %  52.06 MH/s   12/0/0 1965  6800   196 W  265.59 KH/W |
|  4  3080   62 100 %  87.28 MH/s   21/0/0 1845  9251   324 W  269.38 KH/W |
|  5  3070   65  44 %  52.06 MH/s   16/0/0 1965  6800   202 W  257.70 KH/W |
|  6  3070   67  69 %  52.06 MH/s   13/0/0 1920  6800   197 W  264.25 KH/W |
|  7  3070   72  82 %  52.06 MH/s   13/0/0 1920  6800   196 W  265.60 KH/W |
|                     522.33 MH/s  127/0/0             1774 W  294.44 KH/W |
+---+-----+----+-----+-----------+--------+----+-----+-------+-------------+
03:08:12 Pool: eth.f2pool.com:6688 Shares/Minute: 3.90
03:08:12 Pool Hashrate: 558.87 MH/s Efficiency: 107.00 %
03:08:12 Uptime: 0d 00:32:32 Electricity: 0.961 kWh

That does'nt seem to change much still decreasing over time that's fucking crazy

**Comment by elestranobaron** [comment]
+---+-----+----+-----+-----------+--------+----+-----+-------+-------------+
| ID  GPU  Temp  Fan     Speed     Shares  Core  Mem   Power   Efficiency  |
+---+-----+----+-----+-----------+--------+----+-----+-------+-------------+
|  0  3080   58  98 %  80.17 MH/s   28/0/0  855  9251   210 W  381.76 KH/W |
|  1  3090   64 100 %  89.81 MH/s   38/0/0  810  9501   246 W  365.10 KH/W |
|  2  3070   65  35 %  52.06 MH/s   21/0/0 1920  6800   202 W  257.71 KH/W |
|  3  3070   58  36 %  52.06 MH/s   21/0/0 1965  6800   197 W  264.24 KH/W |
|  4  3080   64 100 %  87.31 MH/s   34/0/0 1845  9251   302 W  289.10 KH/W |
|  5  3070   66  47 %  52.06 MH/s   20/0/0 1965  6800   205 W  253.93 KH/W |
|  6  3070   68  70 %  52.06 MH/s   17/0/0 1920  6800   199 W  261.60 KH/W |
|  7  3070   72  84 %  52.06 MH/s   19/0/0 1920  6800   198 W  262.92 KH/W |
|                     517.58 MH/s  198/0/0             1759 W  294.25 KH/W |
+---+-----+----+-----+-----------+--------+----+-----+-------+-------------+
03:30:14 Pool: eth.f2pool.com:6688 Shares/Minute: 3.63
03:30:14 Pool Hashrate: 519.65 MH/s Efficiency: 100.40 %
03:30:14 Uptime: 0d 00:54:33 Electricity: 1.606 kWh


non sense at all

plus the fact i could run more than 1000W of cards on a 800 PSU

**Comment by rollindea** [comment]
3080 and 3090 might be Thermal throttling because of to high VRAM-Temps. When that happens the Fan speed immediately rises to 100%. By any chance Founder-Edition cards?

**Comment by rollindea** [comment]
+---+-----+------+-----+-----------+------+----+-----+-----+-------------+
| ID  GPU   Temp   Fan     Speed    Shares Core  Mem  Power  Efficiency  |
+---+-----+------+-----+-----------+------+----+-----+-----+-------------+
|  0  3090  42/90  90 % 120.33 MH/s  695/0 1140 10601 295 W  407.90 KH/W |
|  1 1660S     43 100 %  35.06 MH/s  220/0 1260  8200  92 W  381.06 KH/W |
|  2  2080  39/54  65 %  44.09 MH/s  256/0 1260  7899 104 W  423.94 KH/W |
|                       199.48 MH/s 1171/0            491 W  406.27 KH/W |
+---+-----+------+-----+-----------+------+----+-----+-----+-------------+

Thats how a 3090 should look like. MSI 3090 Suprim X

**Comment by rollindea** [comment]
By the way, it looks like you have very bad OC-Settings. You should try to educate yourself about the right OC-Settings. Its a quick and easy google-search. And a very profitabel search for yourself.

**Comment by elestranobaron** [comment]
Thats what i was thinking 

3090 heat throttle
3080 msi suprix x 10 go termal throttling
3080 asus tuf marginal termal throttling


Thank you for that do you suggest something like afterburner ?

Does that work for all

**Comment by elestranobaron** [comment]
WHat i wonder is how a PSU 800W can run three 300w cards without faulting

**Comment by elestranobaron** [comment]
Overclock on linux is to be set manually. But strangely you need xserver and cant do that on some termcaps or libncurse shit

this is what i want to wait because basically decreasing power limit and increasing frequency shouldnt need a lot of marketing macdonalds fancy buttons

and i still dont know about impact on lifetime

so unless theres a good and proper old good termcap version im not sure im going to try that

**Comment by rollindea** [comment]
210+246+302= 758

isn't that complicated
