### ISSUE TITLE
PC Restart

### ISSUE THREAD

**Issue by Asmodeoth** [develsoftware/GMinerRelease#382]
Hi guys, with the new version 2.68 when i start mining my PC just restart, i have w10 and 3080ti, 2.67 runs without problems

**Comment by nguyenhathienphu** [comment]
ran and not restart

**Comment by RisenSamurai** [comment]
Try to downclock your GPU, maybe OC was too high.

**Comment by Asmodeoth** [comment]
> 
> 
> Try to downclock your GPU, maybe OC was too high.

Without overclock same problem, others miners works fine, i just format new OS, and continue restart when start mining

**Comment by RisenSamurai** [comment]
Then check you RAM, I had same problem and the reason was my cheap RAM it did not want to work on 3200mhz speed correctly.

**Comment by Asmodeoth** [comment]
> 
> 
> Then check you RAM, I had the same problem and the reason was my cheap RAM it did not want to work on 3200mhz speed correctly.

only have this problem with v2.68, 2.67 works fine
