### ISSUE TITLE
v1.75 / v1.76 Dual mining ETH+CKB data missing in stats api

### ISSUE THREAD

**Issue by RainbowMiner** [develsoftware/GMinerRelease#42]
Thank you for adding dual mining ETH+CKB. Unfortunatly you might have forgotten to add the CKB statistics (hashrate, accepted/rejected shares) to your stats API. Please add this :)

**Comment by RainbowMiner** [comment]
The current version 1.76 still does not show Eaglehash hashrate and accepted/rejected shares on its localhost API. Please add this. I cannot enable Gminer dual mining for RainbowMiner, until I can read the data from the stats API.

**Comment by develsoftware** [comment]
thank you for feedback, we will fix this issue in next update, approx. tomorrow

**Comment by RainbowMiner** [comment]
Perfect, thank you very much in advance.

**Comment by RainbowMiner** [comment]
Thank you! I confirm it works like a charm in v1.77 - I have already included Gminer's dual mining capability in the latest RainbowMiner release.
