### ISSUE TITLE
gminer terminated when ubuntu upgraded from 21.04 to 21.10

### ISSUE THREAD

**Issue by zysyusi** [develsoftware/GMinerRelease#440]
The log file like below.
![image](https://user-images.githubusercontent.com/48871976/137629393-4179ba00-be91-4436-89eb-53b1fe46feb3.png)

GPU is nvidia a4000.
![image](https://user-images.githubusercontent.com/48871976/137629995-fe2470b6-e2a3-4370-805d-a599389f0ad3.png)

Nvidia driver version is 470.57.02.
![image](https://user-images.githubusercontent.com/48871976/137629539-aa29589e-4ae1-4220-b1e7-9bd42875af34.png)

The linux kernel version is 5.13.0.
![image](https://user-images.githubusercontent.com/48871976/137629636-ae132263-50cd-4bf0-b473-28ecfa6ea832.png)

Does anyone know how to solve it (except donwgrade to 21.04)

**Comment by klard001** [comment]
gminer_2_70 is throwing this kernel error
Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
segfault at 0 ip 0000000000000000 sp 00007ffc50242348 error 14 in miner[400000+1e26000]

**Comment by DeeDeeRanged** [comment]
This project is not dead you might be better of reporting on https://bitcointalk.org/index.php?topic=5034735.2480

**Comment by verdelyi** [comment]
You could try the podman workaround I suggested in #470 for the time being.

**Comment by zysyusi** [comment]
gminer2.72 solves this problem. Thanks!
