### ISSUE TITLE
2.71 has a lower efficiency with 3080 LHR compared to 2.70

### ISSUE THREAD

**Issue by fcthemaster** [develsoftware/GMinerRelease#480]
My 3080 LHR with this options --lock_cclock 1060  --mclock 1100 with the 2.70 has a power consumption oh 170/175w and 88-90° of memory temperature.
Now I have 204w of power consumption and 98-100° of memory temp, with the same hashrate (65-67 MH/s).

**Comment by develsoftware** [comment]
use --lhr_mode 0

**Comment by fcthemaster** [comment]
i receive "unknown argument"
