### ISSUE TITLE
Question about EVGA 3070 TI XC3

### ISSUE THREAD

**Issue by mtmtmt123** [develsoftware/GMinerRelease#486]
Hello, I have a Evga XC3 3070TI , i try to install EVGA Precision to deactivate RGB Light but if i run the Tool it needs to Update Firmware, Affect this the Mining Lock or Speed ?
Anyone have Updated the Firmware?

**Comment by dedizones** [comment]
no update for mining and all new RTX is affect by LHR system ;)

**Comment by powpppp** [comment]
pow

ในวันที่ ศ. 19 พ.ย. 2021 15:41 น. mtmtmt123 ***@***.***>
เขียนว่า:
