### ISSUE TITLE
Hotspot temperature

### ISSUE THREAD

**Issue by zulu1905** [develsoftware/GMinerRelease#512]
Would you consider adding a hotspot temperature display?

The reason I want this is because most of the cards do not have a memory temperature indicator, the hotspot temperature on the cards is very close  or same as the memory temperature.

**Comment by brgabriel09** [comment]
There is no reason for this to exist in gminer. Use other third-party software that measure and calculate the temperature based on other things. Or simply add a temperature probe on your memory chip and done.
