### ISSUE TITLE
dag_mode 1 and 2

### ISSUE THREAD

**Issue by zulu1905** [develsoftware/GMinerRelease#528]
can you explain dag mode 1 and 2 single or dual buffer ? what is the difference between this two modes. when should we use a dual or single buffer ?

**Comment by dedizones** [comment]
this parameter is used to cache the next ETH day but if you have an overclocking well done, the simple dag is now sufficient another option is used the generation of the day card by card longer but more stable

--dag_gen_limit - maximal number of parallel DAG generations, 0 - disable limit, default value is '0' (for example: '3')

I have put "--dag_gen_limit 1" for generation dag one by one
