### ISSUE TITLE
Automatic creation of a log file when the miner starts

### ISSUE THREAD

**Issue by taqyon** [develsoftware/GMinerRelease#574]
### Hi!
Is there any way to configure the miner so that it creates a new log file on startup? It is very inconvenient that the program writes logs in the same file. In scenarios where there are errors with the hardware, it is difficult to see long logs.

**Comment by sjcdcheu** [comment]
May be by daily and use the date code, i.e. worker-MM-DD-YY.log when the day change at mid-night.  Amend when same operator log in on the same day.

**Comment by taqyon** [comment]
> May be by daily and use the date code, i.e. worker-MM-DD-YY.log when the day change at mid-night. Amend when same operator log in on the same day.

For a start, it would be cool to just create a file with a new session

**Comment by xb3l13v3r** [comment]
I would appreciate this too... any examples of how to get gminer to make daily logs?
