### ISSUE TITLE
Impossible to choose only AMD cards in HIVEOS

### ISSUE THREAD

**Issue by snowballss** [develsoftware/GMinerRelease#604]
In Hiveos if used mixed rig AMD+NVIDIA cards it is impossible to choose only AMD cards in the flight sheet. The problem is that you will have "GPU 0" for NVIDIA and "GPU 0" for AMD cards at the same time. GMiner allows you to choose only by number. If I set GPU 0 for the AMD card the miner refuses to work. For example, this is not an issue if I use lolMiner where I can set only AMD cards by argument "--devices AMD". But for mining Flux, there is no choice but GMiner because in lolMiner the hash rate is much lower for Flux

![12122123](https://user-images.githubusercontent.com/16793330/150626610-72e25e45-c85a-49ba-b165-c72bee5fdc23.jpg)

**Comment by pdieppa** [comment]
Have you tried running this GMiner command to see what you get?
--list_devices

**Comment by snowballss** [comment]
Does it work in hiveos? I think it is for windows.


![333333](https://user-images.githubusercontent.com/16793330/150652260-0fa8624c-771b-4079-9a12-3aaf78b6cb02.jpg)

**Comment by pdieppa** [comment]
Remove all other commands.

**Comment by snowballss** [comment]
It is obvious you don't have the Hiveos. You can't create an empty flight sheet or I don't know the way. You must define algo you mine, worker name + wallet, then define pool address. After that and only that I can put some commands there. Without anything and just only one command "--list_devices" it gives me a bunch of errors. Plus if you go to Gminer ReadMe there is only --cuda_devices argument. But this gives me the same errors.

![55555](https://user-images.githubusercontent.com/16793330/150655413-6df046b1-b862-49d8-8a75-f804bc918f94.jpg)

![7777](https://user-images.githubusercontent.com/16793330/150655419-561a2ae0-8e4c-453e-93ba-187b48a67dbe.jpg)

![8888](https://user-images.githubusercontent.com/16793330/150655423-8d08dcf8-23e7-4e17-922e-0c1f80188e56.jpg)

![455454545](https://user-images.githubusercontent.com/16793330/150655468-7d132c00-17ff-4986-8ea9-b840093c527b.jpg)

![88888888](https://user-images.githubusercontent.com/16793330/150655471-beb4594a-6d9c-4a07-8e93-0b3948bc83ec.jpg)

I think I will wait for my others 6800xt and create a separate rig using Windows. Because even the Gminer has a bs hash rate for Flux than TeamRedMiner. 49 Sol/s vs 66 Sol/s. Don't have any time left for fighting the Gminer under hiveos. Do make the simple argument like in lolMiner (--devices AMD) or do not I don't care. I will stick with another miner.

**Comment by pdieppa** [comment]
I use HiveOS everyday. You need to run that command from the shell. I thought you knew that. Sorry about that.

**Comment by pdieppa** [comment]
I also found this in the documentation
--cuda - enable/disable CUDA platform ('0' - off or '1' - on), default value is '1'
--opencl - enable/disable OpenCL platform ('0' - off or '1' - on) , default value is '1'

**Comment by snowballss** [comment]
So, how to do step by step because I don't get it. For example, I use shellinabox. Just click on my IP address in GUI and then in the newly opened window I put my credentials user and pass. Then just type "miner" and I can see how miner is working. 

![111111](https://user-images.githubusercontent.com/16793330/150656609-8d011365-f8ec-4b33-8f27-a8c2f46d8ab8.jpg)

I tried new arguments here

![2222](https://user-images.githubusercontent.com/16793330/150656677-42992f45-8d73-47a5-a75c-65aa714e254d.jpg)

then I receive the same error if I would choose just GPU 0. 

![77777](https://user-images.githubusercontent.com/16793330/150656827-c2973dac-4556-483d-b84f-7c3234de9242.jpg)

I was running this for a couple of minutes.  Returned my lolminer flight sheet and now it stopped working at all. Pool just blocking me or something. I think I am done with experiments. Thank you for your help.

**Comment by pdieppa** [comment]
One thing at a time.
Your current error is because your login is formatted incorrect. It should be:
WALLET.WORKERNAME and not WALLET/WORKERNAME

Try that first

**Comment by pdieppa** [comment]
From a new shell session, type **miner stop** to stop mining

Then type **cd/hive/miners/gminer** and press enter
type **ls** and press enter to view the versions you have installed.
Pick the version you are using and type **cd** type the version and press enter.


This will put you in the gminer folder.
From there you can type **gminer ---list_devices** and press enter

**Comment by snowballss** [comment]
YAY! I love you =) Thank you so much and especially for your patience. It is working now. I put screenshots here maybe it will help someone too.

![9999](https://user-images.githubusercontent.com/16793330/150657582-ae072037-853a-4e1c-bb6f-47765a8d0a08.jpg)

![10101010](https://user-images.githubusercontent.com/16793330/150657588-86107e5f-e229-49ff-a28e-2dcaeb9fd34a.jpg)

**Comment by pdieppa** [comment]
I'm glad you got it figured out.
