### ISSUE TITLE
Dev fee

### ISSUE THREAD

**Issue by girtsjj** [develsoftware/GMinerRelease#610]
Not an issue really. More of querry for clarification. 
As from 2.75 miner has 1% fee. Does older versions still have 0.65%? It does say 0.65 when miner starts on version 2.74 but wondering if it is built into miner or it rings back home to find out what fee to charge? I dont mind paying a fee. But i dont need all the bells and whistles that is meant mainly for LHR cards as all mine are non LHR. If i can save 0.35%.. Why not?

**Comment by tuntin2022** [comment]
1% no matter v2.73 or v2.74 - it does call home

**Comment by FMEM** [comment]
老版本也是百分之1了吗？开发费？不升级也是百分之1？

**Comment by nrpeyton** [comment]
E.T. Phone Home.
