### ISSUE TITLE
[BUG] - Connection failing

### ISSUE THREAD

**Issue by g126** [develsoftware/GMinerRelease#620]
+----------------------------------------------------------------+
|                          GMiner v2.76                          |
+----------------------------------------------------------------+
Algorithm:          Ethash
DevFee:             1 %
Server #1:          
  host:             eth.f2pool.com:6688
  user:             ***
  password:         ****
Server #2:          
  host:             eth-backup.f2pool.com:6688
  user:             ***
  password:         ****
Power calculator:   on
Color output:       on
Watchdog:           on
API:                off
Log to file:        miner.log
Selected devices:   GPU0  
Intensity:          100   
Temperature limits: 90/120
------------------------------------------------------------------
16:43:41 Nvidia Driver: 511.65
16:43:42 Connect to eth-na.f2pool.com:6688 Failed: Host not found
16:43:52 Connect to eth-na.f2pool.com:6688 Failed: Host not found
16:44:02 Connect to eth-na.f2pool.com:6688 Failed: Host not found
16:44:13 Connect to eth-backup.f2pool.com:6688 Failed: Host not found
16:44:23 Connect to eth-backup.f2pool.com:6688 Failed: Host not found
16:44:34 Connect to eth-backup.f2pool.com:6688 Failed: Host not found
 
But it works with older version:

+----------------------------------------------------------------+
|                          GMiner v2.74                          |
+----------------------------------------------------------------+
Algorithm:          Ethash
DevFee:             0.65 %
Stratum server #1:
  host:             eth-na.f2pool.com:6688
  user:             ***
  password:         ***
Stratum server #2:
  host:             eth-backup.f2pool.com:6688
  user:            ***
  password:         ****
Power calculator:   on
Color output:       on
Watchdog:           on
API:                off
Log to file:        miner.log
Selected devices:   GPU0
Intensity:          100
Temperature limits: 90/120
------------------------------------------------------------------
16:59:38 Nvidia Driver: 511.65
16:59:38 Connected to eth-na.f2pool.com:6688 [172.65.210.108]
16:59:38 Subscribed to Stratum Server
16:59:38 Set Extra Nonce: b6d7
16:59:38 Authorized on Stratum Server
16:59:38 New Job: 9cd1b95b60509 Epoch: #472 Diff: 8.589G
16:59:38 Started Mining on GPU0: ASUS NVIDIA GeForce RTX 3090 24GB [0000:01:00.0]
16:59:39 New Job: 9cd2815b6050a Epoch: #472 Diff: 8.589G
16:59:41 New Job: 9cd3495b6050b Epoch: #472 Diff: 8.589G
16:59:42 New Job: 9cd4d95b6050c Epoch: #472 Diff: 8.589G
16:59:44 New Job: 9cd5a15b6050d Epoch: #472 Diff: 8.589G
16:59:45 New Job: 9cd7315b6050e Epoch: #472 Diff: 8.589G

**Comment by eosphor** [comment]
With Nicehash i have same problem

**Comment by Forsaken123456** [comment]
i guess that's related to DNS over HTTPS new feature!
how to disable this option? no documentation regarding this
