### ISSUE TITLE
Failed host not found !!!

### ISSUE THREAD

**Issue by zulu1905** [develsoftware/GMinerRelease#632]
![gminer](https://user-images.githubusercontent.com/21012254/154821872-1c7d4d7a-53e1-4f7a-bff4-fad9a09ea47c.PNG)

**Comment by li2518888** [comment]
![双挖不正常啊](https://user-images.githubusercontent.com/100082103/154849315-65ac984c-6012-49ba-af20-5dc6f0cf65b2.png)

The same problem, it is normal to mine Ethereum alone,
