### ISSUE TITLE
[TON] Connection Error: Malformed server message v2.81 and 2.82

### ISSUE THREAD

**Issue by Tareku99** [develsoftware/GMinerRelease#666]
Hello! POrobably something really dumb but with both 2.81 and 2.82 I keep getting this error message of malformed server message. I added the bat file here, let me know what I am doing wrong!
miner.exe --devices 1 --pl 55 --templimit 80 --cclock -400 --mclock 1400 --fan 65 --algo eth+ton --color 1 --watchdog 1 --pec 1 --api 10555 --logfile miner.log --server us1.ethermine.org:4444 --user USER --dserver server1.whalestonpool.com:443 --dssl --duser DUSER

**Comment by Tareku99** [comment]
> miner.exe --devices 1 --pl 55 --templimit 80 --cclock -400 --mclock 1400 --fan 65 --algo eth+ton --color 1 --watchdog 1 --pec 1 --api 10555 --logfile miner.log --server us1.ethermine.org:4444 --user USER --dserver https://server1.whalestonpool.com:443 --dssl --duser DUSER

I copied and pasted this and it still gave the same error. Tested with 2.82..
Am I doing something wrong ?

**Comment by jaehwan-jeon** [comment]
--dserver stratum+tcp://tcp.whalestonpool.com:4001 --duser DUSER

**Comment by Tareku99** [comment]
Thank you. I did a tiny spelling issue.. the fix with the https works fine ! Thanks yall

**Comment by 73183861** [comment]
Ayuda con es te problema error de conexión mensaje de servidor con formato incorrecto gracias 
![IMG_20240402_142523](https://github.com/develsoftware/GMinerRelease/assets/165834335/200728dc-3860-4138-8779-281e2d805a32)
