### ISSUE TITLE
config.txt file questions for ETH+TON

### ISSUE THREAD

**Issue by Tareku99** [develsoftware/GMinerRelease#671]
Anyone has a template of the config file with both eth and ton ? 
I have been using the config file for solo eth mining and works fine but when I edit it for ETH+TON; the cmd does not open at all! Can't get it to work...

Current layout (edited) -- still not working.

[common]
stuff

# Main pool
[server]
host=us1.ethermine.org
port=4444
user=

[dserver]
dserver=tcp.whalestonpool.com:4001
user=

**Comment by rise-worlds** [comment]
dserver=tcp.whalestonpool.com:4001

**Comment by Tareku99** [comment]
> dserver=tcp.whalestonpool.com:4001

nope. the cmd will not even open as of right now, I think the formatting is wrong but I don't know the right way with eth+ton

**Comment by Tareku99** [comment]
> dserver=tcp.whalestonpool.com:4001

![image](https://user-images.githubusercontent.com/25750256/156078500-400c9796-9ffb-40d6-8a1c-7aceff80ad91.png)
this is what the cmd shows if i add what you said..

**Comment by Tareku99** [comment]
For those who still need.. I figured it out: 

[dserver]
host=tcp.whalestonpool.com
port=4001
user=
worker=
