### ISSUE TITLE
toncoinpool.io can be connected but hashrate is zero[v2.85]

### ISSUE THREAD

**Issue by edisonchan** [develsoftware/GMinerRelease#691]
![image](https://user-images.githubusercontent.com/8596506/156951913-6229f74b-4861-4855-ab11-599d1b786019.png)
![image](https://user-images.githubusercontent.com/8596506/156952886-5a7a68e7-47f1-44f0-b55f-2ed255e94bc9.png)

**Comment by trhogne** [comment]
SAme here, and like you, with a nvidia 3050, so i am guessing that the issue is the model  .

**Comment by trhogne** [comment]
Works now with 2.86 release using this .bat
miner.exe --algo ethash --server eth.hiveon.com:4444 --user yourethwallet --dalgo ton --dserver wss://eu1.stratum.ton-pool.com/stratum --duser yourtoncoinwallet

TY for fix
