### ISSUE TITLE
3070Ti+ wattage ripple 

### ISSUE THREAD

**Issue by Blues2121** [develsoftware/GMinerRelease#707]
![IMG_20220314_182209](https://user-images.githubusercontent.com/101578367/158204515-eba4712b-273f-4a67-b0ef-9e0706507362.jpg)
Hi,
I upgraded to Gminer 2.88(Hiveos version 0.6-213@220313). I have 2 3070ti cards. With this version, the wattage drops to 60w twice a day for each card, and returns to normal again. What is the reason of this?
(Dual miner Eth+ton)
(oc setting; core:1185, mem:2000, pl:0)
(Nvidia verson: 470.86)

Thanks,

**Comment by dedizones** [comment]
hi, edit OC and select P0 ? caution P0 add +400mhz oc

you have 2000 + 400 = 2400MHz in real OC

or try upgrade driver: 495.46

nvidia-driver-update 495.46 --force

**Comment by Blues2121** [comment]
Hi,
Since Minner is away, I can't look at the wall, but I've made all the updates and will watch.

Thanks you.

**Comment by Blues2121** [comment]
Hi,

It got fixed after the updates.

Thanks you.

> hi,
> 
> don't check stats watt in hiveos but directly in wattometre system or in on the wall
> 
> edit OC and select P0 ? caution P0 add +400mhz oc
> 
> you have 2000 + 400 = 2400MHz in real OC
> 
> or try upgrade driver: 495.46
> 
> `nvidia-driver-update 495.46 --force`
> 
> **for update linux:**
> 
> `sudo apt-get update -y && sudo apt-get dist-upgrade -yuf` `sudo apt-get install nvidia-settings xserver-xorg-core --allow-change-held-packages -y`
> 
> **more space ssd:**
> 
> `disk-expand`

**Comment by Blues2121** [comment]
Thanks
