### ISSUE TITLE
3060ti lhr not detect

### ISSUE THREAD

**Issue by zulu1905** [develsoftware/GMinerRelease#717]
can you add force lhr mode i think this card is new  (board id 2414) and gminer not detecting as lhr. but lolminer and t-rex  are detecting as lhr this card.

**Comment by zulu1905** [comment]
GA103-A  3060ti lhr detection not working, can you add this card

**Comment by FranciscoQuero** [comment]
I'm experiencing the same issue. Even if I try with the --lhr or --lhr-tune options, LHR unlock does not work

**Comment by FranciscoQuero** [comment]
@zulu1905 try with the new version 2.90, this version should fix the issue!

**Comment by zulu1905** [comment]
working now with  v2.90
