### ISSUE TITLE
Version 2.91 / Windows 11.0: Anti-hacking system detected modification of the miner memory

### ISSUE THREAD

**Issue by UselessGuru** [develsoftware/GMinerRelease#732]
When run as powershell process I get 'Anti-hacking system detected modification of the miner memory.' error messages.

Code used to launch miner is based on https://github.com/FuzzySecurity/PowerShell-Suite/blob/master/Invoke-CreateProcess.ps1

If miner is run in CMD window all is working fine. Also older Versions up to 2.90 did not 'misbehave'

**Comment by UselessGuru** [comment]
This helped in my case:

https://github.com/develsoftware/GMinerRelease/issues/135#issuecomment-882825895

I am developing powershell code for www.nemosminer.com using Visual Studio Code (which has a debugger attached).
When run outside of VSC gminer works just fine.

**Comment by mabreuortega** [comment]
Having the same issue for 2.94
Running in the console with driver 512.77
