### ISSUE TITLE
Gminer ETC invalid Need help

### ISSUE THREAD

**Issue by JellyTOP** [develsoftware/GMinerRelease#737]
![image](https://user-images.githubusercontent.com/35587996/161955758-d69b55cb-0937-4dbc-a415-3d1bf14379fb.png)
![image](https://user-images.githubusercontent.com/35587996/161955953-844f1573-990b-4642-8602-2c9eb59a96d3.png)

**Comment by UselessGuru** [comment]
Pls. post the command line parameters used to run the miner.

**Comment by pdieppa** [comment]
Maybe the OC settings for the 6700XT need to come down a bit. I see the power is at 113 watts and should be around 89 to 95 watts (software reported).

**Comment by JellyTOP** [comment]
miner.exe --algo ethash --server asia1-etc.ethermine.org:4444 --user wallet.bot --intensity 100
pause

**Comment by JellyTOP** [comment]
> 请。发布用于运行矿工的命令行参数。

miner.exe --algo ethash --server asia1-etc.ethermine.org:4444 --user wallet.bot --intensity 100
pause

**Comment by JellyTOP** [comment]
> Maybe the OC settings for the 6700XT need to come down a bit. I see the power is at 113 watts and should be around 89 to 95 watts (software reported). This is how all my 6700XT are setup under HiveOs
> 
> ![image](https://user-images.githubusercontent.com/74556152/162006232-5490019b-56a2-4568-bc51-774703ae7805.png)
> 
> ![image](https://user-images.githubusercontent.com/74556152/162006434-3fd9ca6a-a176-40d5-97ae-be937ea24f0e.png)

Is it because my power consumption is too high?

**Comment by JellyTOP** [comment]
> Pls. post the command line parameters used to run the miner.

miner.exe --algo ethash --server asia1-etc.ethermine.org:4444 --user wallet.bot --intensity 100
pause

**Comment by JellyTOP** [comment]
> 

![image](https://user-images.githubusercontent.com/35587996/162119649-2b7ce8e2-4c9b-4e4d-81b2-936020b64591.png)

**Comment by JellyTOP** [comment]
> I think the -algo is wrong for etc.
> 
> It should be -algo etchash

Thanks, you're on the right track.
