### ISSUE TITLE
Gminer 2.91 [TON] Connection Error: Malformed server message

### ISSUE THREAD

**Issue by ALOBLE** [develsoftware/GMinerRelease#753]
Hello!
When I'm trying to mine ETH+TON on HiveOS with Gminer 2.91 and other versions lower till 2.82 I receive this message:
**[TON] Connection Error: Malformed server message**
Only 2.80 version works without this error
![1](https://user-images.githubusercontent.com/104319847/164990731-6bc74cdf-dbcf-4f0c-bedd-28299f45fdf8.jpg)
![2](https://user-images.githubusercontent.com/104319847/164990733-19940779-7581-41a8-aee0-2fd6ca090817.jpg)
.

**Comment by zulu1905** [comment]
remove port use this server https://server1.whalestonpool.com    
or   
use this server  with the port  pool.services.tonwhales.com:443

**Comment by zulu1905** [comment]
if it is not work you can try this adresses  too

wss://stratum.whalestonpool.com/stratum
stratum+tcp://tcp.whalestonpool.com:4001

**Comment by ALOBLE** [comment]
> remove port use this server https://server1.whalestonpool.com/

Thank you, now it's working!
