### ISSUE TITLE
Gminer 2.74 restarts

### ISSUE THREAD

**Issue by WagnerBezerra2021** [develsoftware/GMinerRelease#758]
Good morning. I have a problem in gminer 2.74 I have 3 rigs, but one of them is giving an unsolved error because it doesn't generate a log, and it doesn't tell me the problem, the miner just restarts and shows this "error error on gpu3 an illegal process was encoutered ". So I don't know if overclocking, if it's drivers or something else, it gives this error in an average of two days.

**Comment by nrpeyton** [comment]
if it was caused by drivers there'd be thousands of people experiencing the same issue.

The only variable is your overclocks.  

Have you tried removing ALL your overclocks for 2, 3, 4, or more days, etc?

**Comment by WagnerBezerra2021** [comment]
> if it was caused by drivers there'd be thousands of people experiencing the same issue.
> 
> The only variable is your overclocks.
> 
> Have you tried removing ALL your overclocks for 2, 3, 4, or more days, etc?

Thanks for the answer. I lowered the memory overclock of the rtx 2060 super from 1850 to 1800, and so far it's been stable for almost 48h. What left me not knowing what to do, and that in many cases when an overclock error occurs, the program asks to decrease it.
