### ISSUE TITLE
Lower hashrates on 2.92

### ISSUE THREAD

**Issue by girtsjj** [develsoftware/GMinerRelease#766]
As per title. I am getting lower hashrates on my non-lhr rigs on linux and windows pc comparing to 2.91. Latest drivers installed.

**Comment by Miiichal** [comment]
copy of
[](https://github.com/develsoftware/GMinerRelease/issues/763)

**Comment by girtsjj** [comment]
> copy of [((https://github.com/[/issues/763](https://github.com/develsoftware/GMinerRelease/issues/763)))]

How is it copy of?? Look at the title of the issue. There is nothing that indicates hashrates. So i need to go through all irrelevant issues to mine and see if someone hijacked somebodys thread with their issue instead opening their own?

**Comment by unmarked-pl** [comment]
I also recorded a decrease of 0.3 MH/s. Hope the problem fixes quickly.

**Comment by Alkanphel34** [comment]
При запуске от имени администратора пишет следящие, обычным способом запускается но пишет что без прав админа. Драйвер 512.15 OC Win

C:\Windows\system32>miner.exe --algo ethash --server ethash.poolbinance.com:1800 --user test.default
"miner.exe" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

C:\Windows\system32>pause
Для продолжения нажмите любую клавишу . . .

**Comment by girtsjj** [comment]
Solved in 2.93
