### ISSUE TITLE
Error on GPU unknown error. GPU crashes and defaults overclocks.

### ISSUE THREAD

**Issue by EroticPanda** [develsoftware/GMinerRelease#780]
Updating to the latest gminer to take advantage of the new lhr unlocks.
Running Miner with elevated privileges.
After running for about 2min 30 sec watchdog will declare "Error on gpu (0 or 1) unknown error", the ui will hang for a moment, and any overclocks applied to gpu0 and 1 will be defaulted.
Dropping the overclocks significantly will make them no longer crash in this fashion, but their hashrate will be reduced lower than it was with lhr limiting on. In addition, lowering overclocks will then have the effect of watchdog declaring "Error on Gpu 2 unknown error" (the non lhr 3090). The 3090 will continue to run with set overclocks when watchdog restarts but it will restart in this fashion every 2 mins or so.

Rig Specs:
gpu 0,1 3060 LHR 
gpu 2 3090 nonlhr(obviously)
Nvidia 472.12
Gminer 2.96 Windows 64bit

**Comment by magicxs1** [comment]
hav the same, using 470.72 nvidia driver for a 3070 TI under a VMware ESXi.  LHR works (full hashrate) but after 2min or more, the VM crashes.

**Comment by shurx** [comment]
Crashes with driver error 470.63.01 hiveos on 3060 t i hr and 2060 super

**Comment by EroticPanda** [comment]
So, it was absolutely because of the nvidia driver version. I updated to 512.15 Nvidia and it doesn't crash anymore. I should have read the update closer to see it is only supporting 512.xx.
