### ISSUE TITLE
Mining ravencoin not working properly

### ISSUE THREAD

**Issue by ektefa** [develsoftware/GMinerRelease#809]
miner --algo kawpow --server rvn.2miners.com:6060 --user XXX

GPU: RTX 3080 Ti
OS: Windows 11
Nvidia Driver: v512.15

It stucks in this state and nothing happens or sometimes after 5-10mins it starts mining!

Tested versions: Gminer 3.01, 3.02, 3.03, 3.04, 3.05

Also: when it starts mining wrong Balance is shown for rvn on 2miners. For example: my balance is 33.333 but miner shows 3.3333
Looks like one extra division is made when calculating the balance on rvn.

![image](https://user-images.githubusercontent.com/16678574/184384167-ba5a978f-47c4-43fa-9f0b-586e4ff9e7bf.png)

**Comment by monkeyfart34** [comment]
ik this is over 5 monthes old, but you need to delete the :XXXX after the server, and put  --port XXXX.

it should look like this
`miner.exe --algo kawpow --server [REPLACE WITH POOL] --port [PORT #] --user [WALLET]
pause
`
