### ISSUE TITLE
Cortex+zil not enough memory

### ISSUE THREAD

**Issue by Jorgelote** [develsoftware/GMinerRelease#871]
As said on the title, cortex+zil displayed an error of not enough memory if i take off the "zil" command it will start withouth issue, the weird thing is: 
3070 (8gb) does not start mining with zil
BUT 2060 super (8gb): starts mining with zil 
i don't know if there are any other graphic cards with this issue, but if the 3070 has it maybe the 3060 ti too and so on
Could you fix this? Thanks!

**Comment by develsoftware** [comment]
many cards may has mark 8GB, however if you compare MB size of these cards it is not equal, take look to nvidia-smi report on your farm
