### ISSUE TITLE
v3.30: Octopus questions

### ISSUE THREAD

**Issue by UselessGuru** [develsoftware/GMinerRelease#880]
Thank you for the new release. 👍 

What is the fee?
Is AMD support planned?

**Comment by MolochBaal** [comment]
It's 3%, I think is a bit high since T-Rex have 2%

**Comment by UselessGuru** [comment]
@MolochBaal 
Where did you find this information?

**Comment by MolochBaal** [comment]
> @MolochBaal Where did you find this information?

Just launch the miner, the first 3 lines show something like
GMiner v3.30
Algorithm: Octopus
DevFee: 3 %
