### ISSUE TITLE
v3.41 (Windows): KawPow not available for GTX750?

### ISSUE THREAD

**Issue by UselessGuru** [develsoftware/GMinerRelease#895]
`Bin\GMiner-v3.41\miner.exe --nvml 0 --algo kawpow --cuda 1 --opencl 0 --server kawpow.mine.zergpool.com:13638 --ssl 1 --user #########################--pass c=BTC,mc=XNA,ID=#########,pl=0 --api 4003 --watchdog 0 --devices 2`

```
+----------------------------------------------------------------+
|                          GMiner v3.41                          |
+----------------------------------------------------------------+
Algorithm:          KAWPOW
DevFee:             2 %
Server:
  host:             ssl://kawpow.mine.zergpool.com:13638
  user:             ###########################
  password:         c=BTC,mc=XNA,ID=###############,pl=0
Power calculator:   on
Color output:       on
Watchdog:           off
API:                http://127.0.0.1:4003
Log to file:        off
Selected devices:   GPU2
Intensity:          100
Temperature limits: 90/120
------------------------------------------------------------------
17:18:30 Nvidia Driver: Unknown
17:18:30 Failed to initialize miner on GPU2: GAINWARD NVIDIA GeForce GTX 750 Ti 2GB [0000:10:00.0]: no kernel image is available for execution on the device
17:18:30 No devices for mining
```

Installed driver version is 531.79. Other Nvidia cards (GT 1030 & GTX 1660 Super) in the same computer are working fine.

**Comment by UselessGuru** [comment]
Any news?

**Comment by ElXanys** [comment]
> `Bin\GMiner-v3.41\miner.exe --nvml 0 --algo kawpow --cuda 1 --opencl 0 --server kawpow.mine.zergpool.com:13638 --ssl 1 --user #########################--pass c=BTC,mc=XNA,ID=#########,pl=0 --api 4003 --watchdog 0 --devices 2`
> 
> 
> 
> ```
> 
> +----------------------------------------------------------------+
> 
> |                          GMiner v3.41                          |
> 
> +----------------------------------------------------------------+
> 
> Algorithm:          KAWPOW
> 
> DevFee:             2 %
> 
> Server:
> 
>   host:             ssl://kawpow.mine.zergpool.com:13638
> 
>   user:             ###########################
> 
>   password:         c=BTC,mc=XNA,ID=###############,pl=0
> 
> Power calculator:   on
> 
> Color output:       on
> 
> Watchdog:           off
> 
> API:                http://127.0.0.1:4003
> 
> Log to file:        off
> 
> Selected devices:   GPU2
> 
> Intensity:          100
> 
> Temperature limits: 90/120
> 
> ------------------------------------------------------------------
> 
> 17:18:30 Nvidia Driver: Unknown
> 
> 17:18:30 Failed to initialize miner on GPU2: GAINWARD NVIDIA GeForce GTX 750 Ti 2GB [0000:10:00.0]: no kernel image is available for execution on the device
> 
> 17:18:30 No devices for mining
> 
> ```
> 
> 
> 
> Installed driver version is 531.79. Other Nvidia cards (GT 1030 & GTX 1660 Super) in the same computer are working fine.

🫡
